

# This file was *autogenerated* from the file RSA.sage
from sage.all_cmdline import *   # import sage library

_sage_const_12 = Integer(12); _sage_const_65537 = Integer(65537); _sage_const_17 = Integer(17); _sage_const_23 = Integer(23)
def RSA(m: int, e: int, p: int, q: int) -> int:
    n = p*q
    ring = Integers(n)
    cipher_text = ring(m) ** e
    return cipher_text

cipher_text = RSA(m=_sage_const_12 , e=_sage_const_65537 , p=_sage_const_17 , q=_sage_const_23 )
print(f'RSA = {cipher_text}')

