

# This file was *autogenerated* from the file Factoring.sage
from sage.all_cmdline import *   # import sage library

_sage_const_510143758735509025530880200653196460532653147 = Integer(510143758735509025530880200653196460532653147); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
if __name__ == '__main__':
    n = _sage_const_510143758735509025530880200653196460532653147 
    primes = qsieve(n)
    p, q = primes[_sage_const_0 ][_sage_const_0 ], primes[_sage_const_0 ][_sage_const_1 ]

    print(f'p = {p}')
    print(f'q = {q}')

    answer = p if p < q else q

    print(f'answer = {answer}')

