

# This file was *autogenerated* from the file RSA.sage
from sage.all_cmdline import *   # import sage library

_sage_const_22663 = Integer(22663); _sage_const_101 = Integer(101); _sage_const_17 = Integer(17)
ring = Integers(_sage_const_22663 )
mod_exp = ring(_sage_const_101 )**_sage_const_17 
print(f'mod_exp = {mod_exp}')

